import React, { useState } from 'react';
import { Download, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from './ui/dialog';
import { Button } from './ui/button';
import { Label } from './ui/label';
import { RadioGroup, RadioGroupItem } from './ui/radio-group';
import { Checkbox } from './ui/checkbox';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  query?: string;
  answer?: string;
}

export function ExportModal({ isOpen, onClose, query, answer }: ExportModalProps) {
  const [format, setFormat] = useState('csv');
  const [includeNarrative, setIncludeNarrative] = useState(true);
  const [isDownloading, setIsDownloading] = useState(false);

  const handleDownload = async () => {
    setIsDownloading(true);
    
    try {
      if (format === 'pdf') {
        // Generate PDF content client-side since /query-pdf endpoint doesn't exist
        if (!query || !answer) {
          throw new Error('No data available to export. Please run a query first.');
        }

        // Create a simple HTML content for PDF generation
        const htmlContent = `
          <html>
            <head>
              <title>Evidence Data Export</title>
              <style>
                body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
                h1 { color: #0055FD; border-bottom: 2px solid #0055FD; padding-bottom: 10px; }
                h2 { color: #333; margin-top: 30px; }
                .query-section { background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0; }
                .answer-section { background: #fff; border: 1px solid #ddd; padding: 20px; border-radius: 8px; }
                .timestamp { color: #666; font-size: 12px; }
              </style>
            </head>
            <body>
              <h1>Evidence Bot - Query Results</h1>
              <div class="timestamp">Generated on: ${new Date().toLocaleString()}</div>
              
              <h2>Query</h2>
              <div class="query-section">
                <p>${query}</p>
              </div>
              
              <h2>Response</h2>
              <div class="answer-section">
                <p>${answer}</p>
              </div>
              
              ${includeNarrative ? `
              <h2>Additional Information</h2>
              <div class="answer-section">
                <p>This evidence was generated by Evidence Bot to support audit and compliance requirements.</p>
                <p>Query executed on: ${new Date().toLocaleString()}</p>
              </div>
              ` : ''}
            </body>
          </html>
        `;

        // Create blob and download
        const blob = new Blob([htmlContent], { type: 'text/html' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `evidence_data_${new Date().getTime()}.html`;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
        
        // Show success toast notification
        toast.success('Evidence data downloaded successfully!', {
          description: 'Your evidence data has been saved as HTML file (can be printed to PDF).',
        });
        
        console.log('Evidence data download completed');
      } else {
        // Handle CSV format
        if (!query || !answer) {
          throw new Error('No data available to export. Please run a query first.');
        }

        const csvContent = `Query,Answer,Timestamp\n"${query.replace(/"/g, '""')}","${answer.replace(/"/g, '""')}","${new Date().toISOString()}"`;
        
        const blob = new Blob([csvContent], { type: 'text/csv' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `evidence_data_${new Date().getTime()}.csv`;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
        
        console.log(`Downloading evidence data as ${format.toUpperCase()} file.`);
        
        // Show success toast notification for CSV
        toast.success('CSV downloaded successfully!', {
          description: 'Your evidence data has been saved as CSV.',
        });
      }
      
      // Close modal after download
      setTimeout(() => {
        onClose();
      }, 500);
    } catch (error) {
      console.error('Error downloading file:', error);
      
      // Show error toast notification
      toast.error('Download failed', {
        description: error instanceof Error ? error.message : 'There was an error downloading your file. Please try again.',
      });
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Export Evidence</DialogTitle>
        </DialogHeader>
        
        <div className="space-y-6">
          {/* Format Selection */}
          <div>
            <Label className="text-sm font-medium mb-3 block">Export Format</Label>
            <RadioGroup value={format} onValueChange={setFormat}>
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="csv" id="csv" />
                <Label htmlFor="csv" className="text-sm">CSV (.csv)</Label>
              </div>
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="pdf" id="pdf" />
                <Label htmlFor="pdf" className="text-sm">PDF (.pdf)</Label>
              </div>
            </RadioGroup>
          </div>

          {/* Actions */}
          <div className="flex gap-3 pt-4">
            <Button onClick={handleDownload} className="flex-1" disabled={isDownloading}>
              {isDownloading ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : (
                <Download className="h-4 w-4 mr-2" />
              )}
              {isDownloading ? 'Downloading...' : 'Download'}
            </Button>
            <Button variant="outline" onClick={onClose} disabled={isDownloading}>
              Cancel
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}